
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "ccd.CCD" --model-hyper-params '{"alpha": 0.0, "batch_size": 16, "c_shuffle_dim": 1, "cf_dim": 64, "d_model": 48, "dropout": 0.2, "enc_in": 7, "f_shuffle_dim": 3, "f_size": 3, "frequency_shuffler": true, "head_dims": 1, "head_dropout": 0.0, "horizon": 96, "individual": false, "layers": 2, "loss": "MAE", "lr": 0.005, "lradj": "type3", "max_number": 5, "norm": true, "num_epochs": 30, "patch_len": 8, "patience": 5, "s_shuffle_dim": 3, "s_size": 3, "sample_rate": 3, "seq_len": 96, "series_dim": 128, "sigma": 1.5, "stride": 8, "v_size": 9}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/CCD" 

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "ccd.CCD" --model-hyper-params '{"alpha": 0.0, "batch_size": 128, "c_shuffle_dim": 1, "cf_dim": 64, "d_model": 24, "dropout": 0.2, "enc_in": 7, "f_shuffle_dim": 3, "f_size": 3, "frequency_shuffler": true, "head_dims": 1, "head_dropout": 0.0, "horizon": 192, "individual": false, "layers": 2, "loss": "MAE", "lr": 0.005, "lradj": "type3", "max_number": 5, "norm": true, "num_epochs": 30, "patch_len": 8, "patience": 5, "s_shuffle_dim": 3, "s_size": 3, "sample_rate": 2, "seq_len": 96, "series_dim": 128, "sigma": 1.5, "stride": 8, "v_size": 9}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/CCD" 

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --model-name "ccd.CCD" --model-hyper-params '{"alpha": 0.0, "batch_size": 128, "c_shuffle_dim": 1, "cf_dim": 64, "d_model": 24, "dropout": 0.2, "enc_in": 7, "f_shuffle_dim": 3, "f_size": 7, "frequency_shuffler": true, "head_dims": 1, "head_dropout": 0.0, "horizon": 336, "individual": false, "layers": 2, "loss": "MAE", "lr": 0.005, "lradj": "type3", "max_number": 3, "norm": true, "num_epochs": 30, "patch_len": 8, "patience": 5, "s_shuffle_dim": 3, "s_size": 2, "sample_rate": 2, "seq_len": 96, "series_dim": 128, "sigma": 1.5, "stride": 8, "v_size": 9}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/CCD" 

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --model-name "ccd.CCD" --model-hyper-params '{"alpha": 0.0, "batch_size": 128, "c_shuffle_dim": 1, "cf_dim": 64, "d_model": 24, "dropout": 0.2, "enc_in": 7, "f_shuffle_dim": 3, "f_size": 3, "frequency_shuffler": true, "head_dims": 1, "head_dropout": 0.0, "horizon": 720, "individual": false, "layers": 3, "loss": "MAE", "lr": 0.005, "lradj": "type3", "max_number": 5, "norm": true, "num_epochs": 30, "patch_len": 8, "patience": 5, "s_shuffle_dim": 3, "s_size": 3, "sample_rate": 2, "seq_len": 96, "series_dim": 128, "sigma": 1.5, "stride": 8, "v_size": 9}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/CCD" 

